// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"760","screenHeight":"768","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"TitleCommandPosition","status":true,"description":"Changes the position of the title command window.","parameters":{"Offset X":"0","Offset Y":"0","Width":"240","Background":"0"}},
{"name":"EnemyBook","status":true,"description":"Displays detailed statuses of enemies.","parameters":{"Unknown Data":"??????"}},
{"name":"ItemBook","status":true,"description":"Displays detailed statuses of items.","parameters":{"Unknown Data":"??????","Price Text":"Price","Equip Text":"Equip","Type Text":"Type"}},
{"name":"WeaponSkill","status":true,"description":"Change skill id of attack for each weapon.","parameters":{}},
{"name":"SimpleMsgSideView","status":true,"description":"at sideview battle, only display item/skill names.","parameters":{"displayAttack":"0","position":"1"}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"atb_core","status":true,"description":"To be an easy, simple and user-friendly, yet powerful atb system\r\n            Serves as the core plugin implementing all atb system essentials","parameters":{"battle_system_code":"atb","base_fill_time":"5","turn_unit_code":"sec","max_turn_unit":"5","wait_cond_code":"full","atb_fill_code":"fill","max_atb_val":"100","atb_rate_code":"update_avg_agi","atb_start_code":"agi","atb_reset_code":"clear","max_linked_input_actors":"-1","no_prior_actor":"false","show_atb_bars":"true","actor_name_w":"123","actor_icon_ox":"6","hp_bar_ox":"6","hp_bar_w":"87","mp_bar_ox":"6","mp_bar_w":"87","tp_bar_ox":"6","tp_bar_w":"87","atb_bar_ox":"6","atb_bar_w":"87","atb_c1":"7","atb_c2":"8","atb_overlay_c1":"19","atb_overlay_c2":"26","atb_bar_text":"AP"}}
];
